import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Kora Center',
      'welcome': 'Welcome to Kora',
      'home': 'Home',
      'news': 'News & Highlights',
      'standings': 'Standings',
      'todays_matches': "Today's Matches",
      'my_teams_only': 'My Teams Only',
      'live': 'Live',
      'scheduled': 'Scheduled',
      'finished': 'Finished',
      'guest_mode': 'Guest Mode',
      'sign_out': 'Sign Out',
      'sign_in': 'Sign In',
      'switch_language': 'Language / اللغة',
      'no_matches': 'No matches scheduled for today.',
      'no_fav_matches': 'No matches scheduled for your favorite teams today.',
      'standings_title': 'League Standings',
      'watch_live': 'Watch Live Stream',
      'video_highlights': 'Video Highlights',
      'trending_news': 'Trending News',
      'select_language': 'Select Language',
      'rank': 'Rank',
      'team': 'Team',
      'played': 'PL',
      'points': 'PTS',
      'gd': 'GD',
      'w_d_l': 'W/D/L',
      'login_title': 'Sign In to Kora',
      'login_subtitle': 'Enter your credentials to continue',
      'email': 'Email Address',
      'password': 'Password',
      'enter_valid_email': 'Please enter a valid email',
      'enter_valid_password': 'Password must be at least 6 characters',
      'logging_in': 'Signing in...',
      'login_failed': 'Login failed. Please check your credentials.',
      'watch': 'Watch',
      'secure_playback': 'SECURE PLAYBACK ACTIVE',
      'protected_stream': 'This transmission is protected by global secure content filters. Any re-broadcast, duplication, or transmission of this stream without written consent is strictly prohibited.',
      'failed_to_load_stream': 'Failed to load video stream',
      'news_highlights_title': 'News & Highlights',
      'login_required_filter': 'Please log in first to toggle and filter favorite teams.',
      'exclusive_streaming': 'EXCLUSIVE STREAMING',
      'promo_title': 'Enjoy HD Highlights & Secure Streaming',
      'promo_subtitle': 'Watch legally with global content coverage',
      'matches_label': 'Matches',
      'news_label': 'News',
      'standings_label': 'Standings',
      'la_liga': 'La Liga',
      'premier_league': 'Premier League',
      'egyptian_league': 'Egyptian League',
      'timeline': 'Timeline',
      'lineups': 'Lineups',
      'streaming': 'Streaming',
      'match_center': 'Match Center',
      'finished_status': 'FINISHED',
      'live_status': 'LIVE',
      'no_events': 'No events available for this match.',
      'starting_xi': 'Starting XI',
      'assist': 'Assist',
      'secure_legal_ott': 'Secure Legal OTT Stream',
      'ott_details': 'This stream supports tokenized HLS/DASH secure integration. Playback is geo-restricted and legal-only.',
      'watch_stream': 'Watch Stream',
      'validating_token': 'Validating premium security token...',
      'stream_link_failed': 'Failed to get streaming link',
      'continue_as_guest': 'Continue as Guest',
      'notifications': 'Notifications',
      'notification_preferences': 'Notification Settings',
      'notification_goals': 'Goal Alerts',
      'notification_match_start': 'Match Kickoff Alerts',
      'notification_match_end': 'Match End Alerts',
      'notification_news': 'Breaking News',
      'notification_promo': 'Promotions & Offers',
      'no_notifications': 'No notifications found',
      'mark_all_read': 'Mark all as read',
      'save_settings': 'Save Settings',
      'profile': 'Profile',
      'name_label': 'Name',
      'email_label': 'Email Address',
      'current_password_label': 'Current Password',
      'new_password_label': 'New Password',
      'confirm_password_label': 'Confirm New Password',
      'update_profile_btn': 'Update Profile',
      'change_password_btn': 'Change Password',
      'profile_updated_msg': 'Profile updated successfully!',
      'password_changed_msg': 'Password changed successfully!',
      'select_avatar_title': 'Select Avatar',
      'toggle_theme': 'Dark Mode',
      'comments': 'Comments',
      'write_comment': 'Write a comment...',
      'no_comments': 'Be the first to comment!',
      'send': 'Send',
    },
    'ar': {
      'app_title': 'كورة سنتر',
      'welcome': 'مرحباً بك في كورة',
      'home': 'الرئيسية',
      'news': 'الأخبار والميديا',
      'standings': 'الترتيب',
      'todays_matches': 'مباريات اليوم',
      'my_teams_only': 'فرقي المفضلة فقط',
      'live': 'مباشر',
      'scheduled': 'قادمة',
      'finished': 'منتهية',
      'guest_mode': 'وضع الزائر',
      'sign_out': 'تسجيل الخروج',
      'sign_in': 'تسجيل الدخول',
      'switch_language': 'اللغة / Language',
      'no_matches': 'لا توجد مباريات مجدولة اليوم.',
      'no_fav_matches': 'لا توجد مباريات مجدولة لفرقك المفضلة اليوم.',
      'standings_title': 'ترتيب الدوري',
      'watch_live': 'مشاهدة البث المباشر',
      'video_highlights': 'ملخصات المباريات',
      'trending_news': 'آخر الأخبار',
      'select_language': 'اختر اللغة',
      'rank': 'الترتيب',
      'team': 'الفريق',
      'played': 'لعب',
      'points': 'نقاط',
      'gd': 'فارق',
      'w_d_l': 'ف/ت/خ',
      'login_title': 'تسجيل الدخول إلى كورة',
      'login_subtitle': 'أدخل بيانات الاعتماد للمتابعة',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'enter_valid_email': 'الرجاء إدخال بريد إلكتروني صالح',
      'enter_valid_password': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
      'logging_in': 'جاري تسجيل الدخول...',
      'login_failed': 'فشل تسجيل الدخول. يرجى التحقق من البيانات.',
      'watch': 'مشاهدة',
      'secure_playback': 'البث الآمن نشط',
      'protected_stream': 'هذا البث محمي بفلاتر المحتوى الآمنة العالمية. يُحظر تماماً أي إعادة بث أو نسخ أو نقل لهذا البث دون موافقة خطية.',
      'failed_to_load_stream': 'فشل تحميل البث المرئي',
      'news_highlights_title': 'الأخبار وملخصات المباريات',
      'login_required_filter': 'الرجاء تسجيل الدخول أولاً لتفضيل وتصفية الفرق المفضلة.',
      'exclusive_streaming': 'بث حصري ومؤمن',
      'promo_title': 'استمتع بملخصات HD وبث آمن للمباريات',
      'promo_subtitle': 'شاهد بشكل قانوني مع تغطية شاملة للمباريات العالمية',
      'matches_label': 'المباريات',
      'news_label': 'الأخبار والميديا',
      'standings_label': 'الترتيب',
      'la_liga': 'الدوري الإسباني',
      'premier_league': 'الدوري الإنجليزي',
      'egyptian_league': 'الدوري المصري',
      'timeline': 'الأحداث',
      'lineups': 'التشكيلة',
      'streaming': 'البث المباشر',
      'match_center': 'مركز المباراة',
      'finished_status': 'منتهية',
      'live_status': 'مباشر',
      'no_events': 'لا توجد أحداث متوفرة لهذه المباراة.',
      'starting_xi': 'التشكيلة الأساسية',
      'assist': 'صناعة',
      'secure_legal_ott': 'بث OTT قانوني وآمن',
      'ott_details': 'يدعم هذا البث دمج HLS/DASH الآمن بواسطة الرموز المميزة. التشغيل مقيد جغرافياً وقانوني فقط.',
      'watch_stream': 'مشاهدة البث',
      'validating_token': 'جاري التحقق من رمز الحماية المميز...',
      'stream_link_failed': 'فشل الحصول على رابط البث',
      'continue_as_guest': 'الدخول كزائر',
      'notifications': 'الإشعارات',
      'notification_preferences': 'إعدادات الإشعارات',
      'notification_goals': 'تنبيهات الأهداف',
      'notification_match_start': 'تنبيهات بداية المباريات',
      'notification_match_end': 'تنبيهات نهاية المباريات',
      'notification_news': 'الأخبار العاجلة',
      'notification_promo': 'العروض والترويج',
      'no_notifications': 'لا توجد إشعارات حالياً',
      'mark_all_read': 'تحديد الكل كمقروء',
      'save_settings': 'حفظ الإعدادات',
      'profile': 'الملف الشخصي',
      'name_label': 'الاسم',
      'email_label': 'البريد الإلكتروني',
      'current_password_label': 'كلمة المرور الحالية',
      'new_password_label': 'كلمة المرور الجديدة',
      'confirm_password_label': 'تأكيد كلمة المرور الجديدة',
      'update_profile_btn': 'تحديث الملف الشخصي',
      'change_password_btn': 'تغيير كلمة المرور',
      'profile_updated_msg': 'تم تحديث الملف الشخصي بنجاح!',
      'password_changed_msg': 'تم تغيير كلمة المرور بنجاح!',
      'select_avatar_title': 'اختر الصورة الشخصية',
      'toggle_theme': 'الوضع الداكن',
      'comments': 'التعليقات',
      'write_comment': 'اكتب تعليقاً...',
      'no_comments': 'كن أول من يعلق!',
      'send': 'إرسال',
    }
  };

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ?? AppLocalizations(const Locale('en'));
  }

  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
