// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH1e3ab_Ji3L6dxZBE3XGzjMglym5IVhw',
    appId: '1:651674886522:web:3a84ab9ff1ba854945f6c3',
    messagingSenderId: '651674886522',
    projectId: 'koralive-pro-x7b4',
    authDomain: 'koralive-pro-x7b4.firebaseapp.com',
    storageBucket: 'koralive-pro-x7b4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVSLYxTKN8bZuxY6ZlT6v4nK6y8PkFjdk',
    appId: '1:651674886522:android:bf29a51cf977f16145f6c3',
    messagingSenderId: '651674886522',
    projectId: 'koralive-pro-x7b4',
    storageBucket: 'koralive-pro-x7b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANcEq2zI6K0SQ_0jWTDXxfDBAMTNtF9LQ',
    appId: '1:651674886522:ios:7fe085d8aab3c48445f6c3',
    messagingSenderId: '651674886522',
    projectId: 'koralive-pro-x7b4',
    storageBucket: 'koralive-pro-x7b4.firebasestorage.app',
    iosBundleId: 'com.example.kora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANcEq2zI6K0SQ_0jWTDXxfDBAMTNtF9LQ',
    appId: '1:651674886522:ios:7fe085d8aab3c48445f6c3',
    messagingSenderId: '651674886522',
    projectId: 'koralive-pro-x7b4',
    storageBucket: 'koralive-pro-x7b4.firebasestorage.app',
    iosBundleId: 'com.example.kora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH1e3ab_Ji3L6dxZBE3XGzjMglym5IVhw',
    appId: '1:651674886522:web:446b96566448768445f6c3',
    messagingSenderId: '651674886522',
    projectId: 'koralive-pro-x7b4',
    authDomain: 'koralive-pro-x7b4.firebaseapp.com',
    storageBucket: 'koralive-pro-x7b4.firebasestorage.app',
  );
}
